[tool.poetry]
name = "genclai"
version = "0.1.0"
description = "CLI Tool to query chat gpt"
authors = ["Eric Hernandez"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
